name: Build and Publish Rust Extension

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-wheels:
    name: Build rust wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        env:
          PYTHON_SYS_EXECUTABLE: ${{ steps.setup-python.outputs.python-path }}
          PYO3_PYTHON: ${{ steps.setup-python.outputs.python-path }}
        with:
          command: build
          args: --release -m Cargo.toml --out dist
          sccache: true

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: rust-wheels-${{ matrix.os }}-py${{ matrix.python }}
          path: dist

  build-sdist:
    name: Build rust sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: -m Cargo.toml --out dist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: rust-sdist
          path: dist

  pypi-publish:
    name: Publish rust package to PyPI
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    permissions:
      id-token: write
    environment:
      name: pypi
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: rust-wheels-*
          path: dist
          merge-multiple: true

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: rust-sdist
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
